// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1Dx8QUE7bcI06tfGLqvXeTF3bu9USSj8',
    appId: '1:376726423548:web:a2a2664ef81726ee509479',
    messagingSenderId: '376726423548',
    projectId: 'last-exam-29f12',
    authDomain: 'last-exam-29f12.firebaseapp.com',
    storageBucket: 'last-exam-29f12.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCel79UwcnGaFcFNME9QGj0w2MV6KbAGg',
    appId: '1:376726423548:android:d35a244751a04420509479',
    messagingSenderId: '376726423548',
    projectId: 'last-exam-29f12',
    storageBucket: 'last-exam-29f12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnWrKLb-9hrdqS6uJF3bEcgiNSFqVv6ow',
    appId: '1:376726423548:ios:57341f9a1a7b222b509479',
    messagingSenderId: '376726423548',
    projectId: 'last-exam-29f12',
    storageBucket: 'last-exam-29f12.firebasestorage.app',
    iosBundleId: 'com.example.lastExam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnWrKLb-9hrdqS6uJF3bEcgiNSFqVv6ow',
    appId: '1:376726423548:ios:57341f9a1a7b222b509479',
    messagingSenderId: '376726423548',
    projectId: 'last-exam-29f12',
    storageBucket: 'last-exam-29f12.firebasestorage.app',
    iosBundleId: 'com.example.lastExam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1Dx8QUE7bcI06tfGLqvXeTF3bu9USSj8',
    appId: '1:376726423548:web:a5dc0db450ebf302509479',
    messagingSenderId: '376726423548',
    projectId: 'last-exam-29f12',
    authDomain: 'last-exam-29f12.firebaseapp.com',
    storageBucket: 'last-exam-29f12.firebasestorage.app',
  );
}
